
development:
  adapter: mysql2
  database: x_development
  username: root
  password: amr
  host: localhost
test:
  adapter: mysql2
  database: x_test
  username: root
  password: amr
  host: localhost
production:
  adapter: mysql2
  database: x_production
  username: root
  password: amr
  host: localhost